language: android

sudo: false
dist: trusty

jdk: oraclejdk8

android:
  components:
    - tools
    - build-tools-26.0.2
    - android-26

env:
  global:
    # COMPONENT_GOOGLE_REPO
    - secure: "OQ/wkORxY2qv4CmAdMxyW4ihRt5GRyxKxQRZpsdjMbwIKf3DlY6vBoNIEQ46sRRLAKOzkQ3LirodbWRCBlDN9WFw4XRsLTveqqtslMGeLf04peazXMIa6rJ22BCDGEmnzRNx6r3JRb9wEK1plNv4u4G9DgQ7ShzbwdZ8A5grlg8="

addons:
  apt:
    packages:
      - curl
      - tar
      - gzip
      - patch
      - openssh-client
      - git
      - ruby

before_cache:
  - rm -f $HOME/.gradle/caches/modules-2/modules-2.lock
  - rm -fr $HOME/.gradle/